@startuml
  class ObraArte{
    - String descripcion
    - char tipo
    - String artista
    - Vendedor V
    -Precio de Compra OG
    +ObraArte()
  }
  abstract class Persona{
  # String nombre
  # String direccion
  }

  class Vendedor{
    +Vendedor()
  }

  class Venta{
    -float Precio de  Compra
    -Vendedor V
    -ObraArte O
    -Comprador C
    -date fecha
    -bool realizada
    +Venta()
    +void GenReporte()
  }

  class InventarioObras{
    -int numero de obras
    -Obra Obras[]
    +InventarioObras()
    +alta()
    +baja()
    +consulta()
    +ClasificarCuadro()
  }

  class Comprador{
    +Comprador()
  }

  InventarioObras *-- ObraArte : Almacena

  ObraArte --* Vendedor : Tiene

  Venta *-- ObraArte : Vende

  Venta *-- Comprador : Compra

  Venta *-- InventarioObras : Verifica

  Persona <|--Comprador

  Persona <|--Vendedor

@enduml
