@startuml
left to right direction
skinparam packageStyle rectangle
actor Osbert
actor Cliente
rectangle Comprar-Cuadro {
  Cliente -- (Venta): <<extends>>
  Osbert -- (Venta): <<extends>>
  Osbert -- ( Alta Cuadro) : <<extends>>
  Osbert -- ( Clasificar Cuadro) : <<extends>>
  Osbert -- ( Generar Reporte) : <<extends>>
}
@enduml
